"""
NCAE Skills Aptitude Assessment questions, answer keys, and program mappings.
Structure per program: list of 50 dicts with keys:
  num, question, a, b, c, d, answer (A/B/C/D), category (hard/soft/specific)
Items 1-20  = Hard Skills
Items 21-35 = Soft Skills
Items 36-50 = Specific Skills
Scoring: hard = correct/20*100, soft = correct/15*100, specific = correct/15*100
"""

PROGRAM_MAP = {
    'BSCS':  'BSCS',
    'BSIT':  'BSIT',
    'BSA':   'BSA',
    'BSBA':  'Entrep',
    'BSHM':  'Entrep',
    'BSEd':  'BSEd',
    'BEEd':  'BSEd',
    'BSN':   'BSN',
    'BSCPE': 'ECE',
    'BSECE': 'ECE',
    'BSCE':  'ECE',
    'BSEE':  'ECE',
    'BSME':  'ECE',
}

DEFAULT_PROGRAM = 'BSIT'


def get_program_key(course):
    return PROGRAM_MAP.get((course or '').upper().strip(), DEFAULT_PROGRAM)


def _q(num, question, a, b, c, d, answer):
    if num <= 20:
        cat = 'hard'
    elif num <= 35:
        cat = 'soft'
    else:
        cat = 'specific'
    return {'num': num, 'question': question, 'a': a, 'b': b, 'c': c, 'd': d,
            'answer': answer, 'category': cat}


# ── BSCS ──────────────────────────────────────────────────────────────────
BSCS = [
    _q(1,  "What is the output of 8 // 2?", "4", "2", "6", "0", "A"),
    _q(2,  "Which operator checks equality?", "=", "==", "!=", "<", "B"),
    _q(3,  "What does debugging mean?", "Design UI", "Remove errors", "Backup", "Deploy", "B"),
    _q(4,  "Which stores multiple values in Python?", "Integer", "List", "Boolean", "Float", "B"),
    _q(5,  "LIFO refers to:", "Queue", "Stack", "Tree", "Graph", "B"),
    _q(6,  "FIFO refers to:", "Queue", "Stack", "Array", "File", "A"),
    _q(7,  "Binary search requires data be:", "Random", "Sorted", "Hidden", "Linked", "B"),
    _q(8,  "Big-O measures:", "Color", "Complexity", "Sound", "Power", "B"),
    _q(9,  "Recursion means:", "Function calls itself", "Compiler", "Database", "Router", "A"),
    _q(10, "An algorithm is:", "Step procedure", "Keyboard", "Cable", "Document", "A"),
    _q(11, "Primary key is used to:", "Style", "Identify record", "Print", "Route", "B"),
    _q(12, "SQL SELECT does:", "Delete", "Retrieve", "Format", "Reboot", "B"),
    _q(13, "Normalization reduces:", "Redundancy", "Volume", "Users", "Bugs", "A"),
    _q(14, "Index improves:", "Security", "Query speed", "Graphics", "Power", "B"),
    _q(15, "NULL means:", "Zero", "No value", "One", "Table", "B"),
    _q(16, "Git is used for:", "Version control", "Email", "Router", "Power", "A"),
    _q(17, "Agile focuses on:", "Iteration", "Rigid phases", "No testing", "Manufacturing", "A"),
    _q(18, "Compiler does:", "Translate code", "Cook", "Route", "Draw", "A"),
    _q(19, "Encapsulation belongs to:", "OOP", "HTML", "TCP", "CRM", "A"),
    _q(20, "Bug fixing is called:", "Modeling", "Debugging", "Styling", "Hosting", "B"),
    _q(21, "A teammate misunderstands instructions. First action?", "Ignore", "Clarify", "Complain", "Leave", "B"),
    _q(22, "Project issue occurs before deadline.", "Panic", "Diagnose", "Quit", "Wait", "B"),
    _q(23, "Team conflict emerges.", "Mediate", "Avoid", "Insult", "Quit", "A"),
    _q(24, "Member misses deadline.", "Discuss", "Ignore", "Delay", "Blame", "A"),
    _q(25, "Requirements change suddenly.", "Adapt", "Refuse", "Stop", "Delay", "A"),
    _q(26, "Bug appears in production.", "Analyze", "Hide", "Ignore", "Panic", "A"),
    _q(27, "You disagree in team meeting.", "Argue", "Respectfully explain", "Walk out", "Ignore", "B"),
    _q(28, "Heavy workload assigned.", "Prioritize", "Complain", "Delay", "Avoid", "A"),
    _q(29, "Client request unclear.", "Ask questions", "Guess", "Ignore", "Cancel", "A"),
    _q(30, "New technology introduced.", "Learn it", "Resist", "Avoid", "Reject", "A"),
    _q(31, "Unexpected system failure.", "Troubleshoot", "Wait", "Blame", "Leave", "A"),
    _q(32, "Peer asks for help.", "Assist", "Ignore", "Mock", "Report", "A"),
    _q(33, "Multiple solutions possible.", "Evaluate options", "Random pick", "Delay", "Copy others", "A"),
    _q(34, "Feedback is given.", "Use it", "Ignore", "Argue", "Reject", "A"),
    _q(35, "Deadline pressure rises.", "Manage time", "Panic", "Stop", "Delay", "A"),
    _q(36, "Supervised learning is used for:", "Prediction", "Cabling", "Formatting", "Printing", "A"),
    _q(37, "Neural networks are related to:", "AI", "CPU fans", "Cables", "Excel", "A"),
    _q(38, "Training data is used to:", "Build model", "Delete users", "Route traffic", "Debug printer", "A"),
    _q(39, "Backend commonly handles:", "Server logic", "Logos", "Mouse", "Sound", "A"),
    _q(40, "REST API commonly uses:", "HTTP", "HDMI", "VGA", "Bluetooth", "A"),
    _q(41, "Database joins combine:", "Tables", "Monitors", "Files only", "Passwords", "A"),
    _q(42, "Phishing is a:", "Cyber threat", "Sorting method", "Language", "Server rack", "A"),
    _q(43, "Encryption protects:", "Data", "Keyboards", "Monitors", "Folders", "A"),
    _q(44, "Firewall mainly provides:", "Security", "Graphics", "Storage", "Audio", "A"),
    _q(45, "System design concerns:", "Architecture", "Fonts", "Batteries", "Paper", "A"),
    _q(46, "Scalability means:", "Handle growth", "Smaller text", "Less memory only", "More bugs", "A"),
    _q(47, "UML is used for:", "Modeling", "Cooking", "Routing", "Cabling", "A"),
    _q(48, "Git branching supports:", "Collaboration", "Printing", "Power", "Graphics", "A"),
    _q(49, "Merge conflict happens when:", "Code overlaps", "Mouse breaks", "CPU melts", "Database gone", "A"),
    _q(50, "Version control tracks:", "Code changes", "Chair inventory", "Cables", "Power", "A"),
]

# ── BSIT ──────────────────────────────────────────────────────────────────
BSIT = [
    _q(1,  "Which device routes packets between networks?", "Router", "Switch", "Hub", "Repeater", "A"),
    _q(2,  "IP address identifies a:", "Network device", "Keyboard", "File", "Document", "A"),
    _q(3,  "SQL is used for:", "Database queries", "Drawing", "Video editing", "Printing", "A"),
    _q(4,  "Firewall mainly provides:", "Security", "Storage", "Power", "Graphics", "A"),
    _q(5,  "HTML is used for:", "Web structure", "OS kernel", "CPU repair", "Cabling", "A"),
    _q(6,  "DNS translates:", "Domain names", "Battery", "Images", "Audio", "A"),
    _q(7,  "LAN means:", "Local Area Network", "Logic Array Node", "Large App Net", "Line Access Node", "A"),
    _q(8,  "HTTP is for:", "Web communication", "Electricity", "Database power", "Storage", "A"),
    _q(9,  "Database stores data in:", "Tables", "Routers", "Cables", "Modems", "A"),
    _q(10, "Phishing is a:", "Cyber threat", "Sorting method", "Browser", "Printer", "A"),
    _q(11, "Cloud computing means:", "Remote services", "Weather study", "CPU cooling", "Wiring", "A"),
    _q(12, "Operating system manages:", "Resources", "Paper", "Only users", "Sound", "A"),
    _q(13, "Backup is for:", "Recovery", "Gaming", "Graphics", "Coding", "A"),
    _q(14, "VPN provides:", "Private connection", "Battery", "Audio", "Power", "A"),
    _q(15, "MySQL is a:", "Database software", "Router", "Editor", "Compiler", "A"),
    _q(16, "Troubleshooting begins with:", "Diagnosis", "Guessing", "Blame", "Delay", "A"),
    _q(17, "Bandwidth measures:", "Network capacity", "Storage", "Screen size", "Power", "A"),
    _q(18, "Patch updates often fix:", "Vulnerabilities", "Tables", "Printers", "Batteries", "A"),
    _q(19, "Subnetting relates to:", "Network segmentation", "Coding style", "Graphics", "Audio", "A"),
    _q(20, "API mainly enables:", "System communication", "Mouse repair", "Printing", "Formatting", "A"),
    _q(21, "User reports problem unclearly.", "Ignore", "Ask clarifying questions", "Blame user", "Close ticket", "B"),
    _q(22, "Team deadline is near.", "Prioritize tasks", "Panic", "Quit", "Delay", "A"),
    _q(23, "Conflict with coworker occurs.", "Mediate", "Insult", "Avoid", "Leave", "A"),
    _q(24, "New system introduced.", "Learn it", "Resist", "Ignore", "Reject", "A"),
    _q(25, "Multiple issues appear at once.", "Triage problems", "Random fix", "Wait", "Complain", "A"),
    _q(26, "Customer is frustrated.", "Listen calmly", "Argue", "Ignore", "Hang up", "A"),
    _q(27, "Instructions are unclear.", "Seek clarification", "Guess", "Stop", "Blame", "A"),
    _q(28, "Unexpected outage occurs.", "Diagnose", "Panic", "Leave", "Delay", "A"),
    _q(29, "Peer asks technical help.", "Assist", "Ignore", "Mock", "Report", "A"),
    _q(30, "Workload increases.", "Manage time", "Complain", "Stop", "Delay", "A"),
    _q(31, "Security concern is found.", "Report immediately", "Hide", "Ignore", "Wait", "A"),
    _q(32, "User gives feedback.", "Use feedback", "Ignore", "Argue", "Reject", "A"),
    _q(33, "Several solutions exist.", "Evaluate options", "Random choice", "Delay", "Copy", "A"),
    _q(34, "Requirements change.", "Adapt", "Refuse", "Stop", "Avoid", "A"),
    _q(35, "Critical ticket escalates.", "Respond quickly", "Ignore", "Delay", "Blame", "A"),
    _q(36, "Switch primarily operates in:", "Networking", "Accounting", "Nursing", "Teaching", "A"),
    _q(37, "Two-factor authentication improves:", "Security", "Graphics", "Power", "Audio", "A"),
    _q(38, "Cybersecurity includes:", "Threat protection", "Cooking", "Marketing", "Printing", "A"),
    _q(39, "Front-end often includes:", "CSS", "Router", "RAM", "Battery", "A"),
    _q(40, "Command line is used to:", "Issue commands", "Draw logos", "Print papers", "Scan only", "A"),
    _q(41, "Database indexing improves:", "Query performance", "Volume", "Sound", "Power", "A"),
    _q(42, "Encryption protects:", "Data", "Cables", "Monitors", "Files only", "A"),
    _q(43, "Web server hosts:", "Web applications", "CPU fans", "Batteries", "Keyboards", "A"),
    _q(44, "Troubleshooting uses root cause:", "Analysis", "Cooking", "Drawing", "Audio", "A"),
    _q(45, "CRM systems help manage:", "Customer relations", "Network cables", "CPU heat", "Battery", "A"),
    _q(46, "Cloud storage is:", "Remote data storage", "Local RAM", "Cable rack", "Printer ink", "A"),
    _q(47, "Virtualization allows:", "Multiple virtual systems", "Faster typing", "Audio editing", "Paper storage", "A"),
    _q(48, "API integration connects:", "Applications", "Monitors", "Keyboards", "Cameras", "A"),
    _q(49, "Incident response addresses:", "Security events", "Layouts", "Audio bugs", "Print jobs", "A"),
    _q(50, "Technical documentation records:", "System information", "Painting", "Furniture", "Wall color", "A"),
]

# ── BSA ───────────────────────────────────────────────────────────────────
BSA = [
    _q(1,  "Assets = Liabilities + ____.", "Equity", "Revenue", "Expense", "Cash", "A"),
    _q(2,  "Which account increases with a debit?", "Assets", "Liabilities", "Revenue", "Equity", "A"),
    _q(3,  "Which account increases with a credit?", "Liabilities", "Expenses", "Drawings", "Assets", "A"),
    _q(4,  "The income statement reports:", "Profit or loss", "Assets", "Equity", "Cash flow", "A"),
    _q(5,  "The balance sheet shows:", "Financial position", "Revenue", "Expenses", "Profit", "A"),
    _q(6,  "Journal entries are used to:", "Record transactions", "Compute taxes", "Create budgets", "Audit reports", "A"),
    _q(7,  "A trial balance checks:", "Equal debits and credits", "Profitability", "Inventory levels", "Cash flow", "A"),
    _q(8,  "Depreciation allocates the cost of:", "Fixed assets", "Inventory", "Cash", "Liabilities", "A"),
    _q(9,  "Auditing primarily ensures:", "Fair presentation", "High profit", "Low tax", "Fast reporting", "A"),
    _q(10, "Taxation refers to:", "Government charges", "Business income", "Employee wages", "Bank loans", "A"),
    _q(11, "Revenue is best defined as:", "Income earned", "Cost incurred", "Asset owned", "Debt owed", "A"),
    _q(12, "Expenses generally:", "Reduce profit", "Increase assets", "Increase equity", "Reduce liabilities", "A"),
    _q(13, "Owner's equity represents:", "Owner's interest", "Debts", "Inventory", "Cash", "A"),
    _q(14, "Cash flow statement reports:", "Cash inflows/outflows", "Equity only", "Revenue only", "Expenses only", "A"),
    _q(15, "The accounting cycle includes:", "Recording and reporting", "Designing systems", "Marketing", "Programming", "A"),
    _q(16, "Financial statements are used for:", "Decision-making", "Drawing", "Audio processing", "Networking", "A"),
    _q(17, "Internal control helps prevent:", "Fraud", "Sales", "Profit", "Inventory", "A"),
    _q(18, "Inventory is classified as:", "Current asset", "Long-term liability", "Expense", "Revenue", "A"),
    _q(19, "Liabilities are:", "Obligations", "Resources", "Income", "Expenses", "A"),
    _q(20, "Net income equals:", "Revenue - Expenses", "Assets - Liabilities", "Cash - Expenses", "Sales - Tax", "A"),
    _q(21, "You notice an error in financial records before submission.", "Ignore it", "Correct and report it", "Hide it", "Delay reporting", "B"),
    _q(22, "You are under tight audit deadlines.", "Panic", "Prioritize tasks", "Stop working", "Ignore tasks", "B"),
    _q(23, "A colleague suggests unethical reporting.", "Agree", "Refuse and report", "Ignore", "Delay", "B"),
    _q(24, "You are assigned multiple reports.", "Manage and prioritize", "Do random work", "Delay", "Stop", "A"),
    _q(25, "Client questions your report.", "Explain clearly", "Ignore", "Argue", "Leave", "A"),
    _q(26, "You discover possible fraud.", "Ignore", "Report immediately", "Hide it", "Delay", "B"),
    _q(27, "Team conflict arises.", "Resolve professionally", "Argue", "Ignore", "Leave", "A"),
    _q(28, "A mistake affects financial statements.", "Correct it", "Hide it", "Delay", "Ignore", "A"),
    _q(29, "You receive critical feedback.", "Use feedback", "Ignore", "Argue", "Reject", "A"),
    _q(30, "Time pressure affects accuracy.", "Focus carefully", "Rush blindly", "Delay", "Stop", "A"),
    _q(31, "New accounting standard introduced.", "Learn it", "Ignore", "Reject", "Delay", "A"),
    _q(32, "Heavy workload assigned.", "Prioritize", "Complain", "Stop", "Delay", "A"),
    _q(33, "Client data is confidential.", "Protect it", "Share it", "Ignore", "Leak it", "A"),
    _q(34, "Audit issue arises.", "Investigate", "Ignore", "Delay", "Hide", "A"),
    _q(35, "You feel overwhelmed.", "Manage stress", "Quit", "Ignore", "Delay", "A"),
    _q(36, "Financial analysis involves:", "Interpreting data", "Drawing", "Audio", "Network", "A"),
    _q(37, "Attention to detail ensures:", "Accuracy", "Delay", "Stop", "Ignore", "A"),
    _q(38, "Compliance ensures:", "Adherence to rules", "Delay", "Stop", "Ignore", "A"),
    _q(39, "Reporting skills involve:", "Clear communication", "Delay", "Stop", "Ignore", "A"),
    _q(40, "Ethics in accounting ensures:", "Integrity", "Delay", "Stop", "Ignore", "A"),
    _q(41, "Analytical skills help in:", "Decision-making", "Delay", "Stop", "Ignore", "A"),
    _q(42, "Time management ensures:", "Timely reports", "Delay", "Stop", "Ignore", "A"),
    _q(43, "Problem-solving helps:", "Resolve issues", "Delay", "Stop", "Ignore", "A"),
    _q(44, "Data interpretation involves:", "Analyzing numbers", "Delay", "Stop", "Ignore", "A"),
    _q(45, "Documentation ensures:", "Record accuracy", "Delay", "Stop", "Ignore", "A"),
    _q(46, "Auditing skills detect:", "Errors", "Delay", "Stop", "Ignore", "A"),
    _q(47, "Communication skills help:", "Clarity", "Delay", "Stop", "Ignore", "A"),
    _q(48, "Decision-making uses:", "Logic", "Delay", "Stop", "Ignore", "A"),
    _q(49, "Professionalism shows:", "Responsibility", "Delay", "Stop", "Ignore", "A"),
    _q(50, "Confidentiality ensures:", "Data protection", "Delay", "Stop", "Ignore", "A"),
]

# ── BSEd (General) ────────────────────────────────────────────────────────
BSED = [
    _q(1,  "What is a lesson plan primarily used for?", "To organize teaching", "To entertain students", "To store grades", "To design classrooms", "A"),
    _q(2,  "Formative assessment is used to:", "Monitor learning", "Give final grades", "Punish students", "End classes", "A"),
    _q(3,  "Summative assessment occurs:", "End of lesson", "Beginning only", "Middle only", "Never", "A"),
    _q(4,  "Bloom's taxonomy focuses on:", "Learning levels", "Class size", "School design", "Student age", "A"),
    _q(5,  "A syllabus outlines:", "Course content", "Classroom seating", "Student names", "Teacher salary", "A"),
    _q(6,  "Teaching strategies include:", "Methods of instruction", "Networking", "Coding", "Drawing", "A"),
    _q(7,  "Differentiated instruction means:", "Adapting to learners", "Same teaching for all", "No planning", "Random teaching", "A"),
    _q(8,  "Classroom rules are important for:", "Order", "Noise", "Delay", "Confusion", "A"),
    _q(9,  "Feedback helps students:", "Improve learning", "Fail faster", "Stop working", "Ignore lessons", "A"),
    _q(10, "Evaluation measures:", "Student performance", "Teacher salary", "Classroom size", "Network speed", "A"),
    _q(11, "Learning objectives should be:", "Clear", "Random", "Hidden", "Complex only", "A"),
    _q(12, "Constructivism emphasizes:", "Active learning", "Passive listening", "Memorization", "Silence", "A"),
    _q(13, "Assessment tools include:", "Quizzes", "Cables", "Audio", "Power", "A"),
    _q(14, "Lesson closure means:", "Summarizing lesson", "Starting class", "Ignoring topic", "Delaying", "A"),
    _q(15, "Instructional materials support:", "Teaching", "Sleeping", "Running", "Drawing", "A"),
    _q(16, "Teaching aids include:", "Visuals", "Network cables", "Audio devices only", "Power tools", "A"),
    _q(17, "Student-centered learning focuses on:", "Learners", "Teacher only", "Classroom", "Content only", "A"),
    _q(18, "Motivation helps:", "Engagement", "Sleep", "Delay", "Ignore", "A"),
    _q(19, "Curriculum refers to:", "Planned learning", "Random topics", "Audio", "Graphics", "A"),
    _q(20, "Assessment validity ensures:", "Accuracy", "Randomness", "Delay", "Copy", "A"),
    _q(21, "A student is struggling.", "Ignore", "Provide support", "Leave", "Mock", "B"),
    _q(22, "Classroom becomes noisy.", "Manage calmly", "Shout", "Ignore", "Leave", "A"),
    _q(23, "Time is limited.", "Prioritize", "Panic", "Stop", "Delay", "A"),
    _q(24, "Student asks question.", "Answer clearly", "Ignore", "Mock", "Leave", "A"),
    _q(25, "Conflict between students.", "Resolve", "Ignore", "Argue", "Leave", "A"),
    _q(26, "Unexpected lesson issue.", "Adapt", "Stop", "Ignore", "Delay", "A"),
    _q(27, "Multiple tasks assigned.", "Manage tasks", "Random", "Delay", "Stop", "A"),
    _q(28, "Feedback received.", "Use feedback", "Ignore", "Argue", "Reject", "A"),
    _q(29, "Lesson ineffective.", "Adjust method", "Stop", "Ignore", "Blame", "A"),
    _q(30, "Student misbehaves.", "Address calmly", "Ignore", "Shout", "Leave", "A"),
    _q(31, "Group activity assigned.", "Collaborate", "Ignore", "Leave", "Delay", "A"),
    _q(32, "Schedule changes.", "Adapt", "Resist", "Stop", "Delay", "A"),
    _q(33, "Student confused.", "Clarify", "Ignore", "Mock", "Leave", "A"),
    _q(34, "Deadline pressure.", "Plan ahead", "Panic", "Stop", "Delay", "A"),
    _q(35, "Difficult class.", "Be patient", "Leave", "Argue", "Ignore", "A"),
    _q(36, "Effective communication ensures:", "Clarity", "Noise", "Delay", "Stop", "A"),
    _q(37, "Lesson planning requires:", "Organization", "Random", "Delay", "Copy", "A"),
    _q(38, "Critical thinking supports:", "Analysis", "Random", "Delay", "Stop", "A"),
    _q(39, "Classroom management ensures:", "Order", "Noise", "Delay", "Stop", "A"),
    _q(40, "Assessment skills measure:", "Student learning", "Delay", "Stop", "Copy", "A"),
    _q(41, "Adaptability helps:", "Handle changes", "Delay", "Stop", "Copy", "A"),
    _q(42, "Time management ensures:", "Efficiency", "Delay", "Stop", "Copy", "A"),
    _q(43, "Creativity improves:", "Teaching methods", "Delay", "Stop", "Copy", "A"),
    _q(44, "Observation helps:", "Evaluate students", "Delay", "Stop", "Copy", "A"),
    _q(45, "Professionalism shows:", "Responsibility", "Ignore", "Delay", "Copy", "A"),
    _q(46, "Decision-making uses:", "Logic", "Random", "Delay", "Stop", "A"),
    _q(47, "Interpersonal skills build:", "Relationships", "Network", "Audio", "Power", "A"),
    _q(48, "Instructional delivery involves:", "Teaching", "Delay", "Stop", "Copy", "A"),
    _q(49, "Student engagement means:", "Active participation", "Sleeping", "Delay", "Stop", "A"),
    _q(50, "Teaching effectiveness is measured by:", "Student learning", "Delay", "Stop", "Copy", "A"),
]

# ── BSN ───────────────────────────────────────────────────────────────────
BSN = [
    _q(1,  "Which of the following is a normal adult body temperature?", "37 degrees C", "35 degrees C", "39 degrees C", "32 degrees C", "A"),
    _q(2,  "Which is part of the 'Five Rights' of medication?", "Right color", "Right patient", "Right mood", "Right time only", "B"),
    _q(3,  "Hand hygiene prevents:", "Infection", "Power loss", "Data loss", "Audio issues", "A"),
    _q(4,  "Blood pressure measures:", "Circulation", "Memory", "Vision", "Hearing", "A"),
    _q(5,  "Respiration refers to:", "Breathing rate", "Memory", "Network speed", "Audio", "A"),
    _q(6,  "Triage is used to:", "Prioritize patients", "Sort files", "Cook food", "Design system", "A"),
    _q(7,  "IV insertion is a:", "Clinical procedure", "Network task", "Coding skill", "Art skill", "A"),
    _q(8,  "Sterile technique prevents:", "Infection", "Audio loss", "Graphics issue", "Power failure", "A"),
    _q(9,  "Documentation must be:", "Accurate", "Delayed", "Hidden", "Random", "A"),
    _q(10, "Vital signs include:", "Temperature", "Keyboard", "Router", "Mouse", "A"),
    _q(11, "Dosage calculation ensures:", "Correct medication amount", "Random amount", "Delay", "Copy", "A"),
    _q(12, "Patient education aims to:", "Inform patient", "Confuse", "Delay", "Ignore", "A"),
    _q(13, "Emergency response starts with:", "Assessment", "Panic", "Leave", "Ignore", "A"),
    _q(14, "Health assessment evaluates:", "Patient condition", "Network speed", "Audio", "Graphics", "A"),
    _q(15, "Infection control reduces:", "Spread of disease", "Power", "Audio", "Memory", "A"),
    _q(16, "PPE is used for:", "Protection", "Style", "Design", "Graphics", "A"),
    _q(17, "Clinical judgment involves:", "Decision making", "Random choice", "Delay", "Copy", "A"),
    _q(18, "Medical records contain:", "Patient data", "Painting", "Audio", "Graphics", "A"),
    _q(19, "Pulse rate measures:", "Heart beats", "Memory", "Audio", "Network", "A"),
    _q(20, "Oxygen saturation measures:", "Oxygen levels", "Power", "Graphics", "Audio", "A"),
    _q(21, "A patient is anxious. What should you do?", "Ignore", "Reassure calmly", "Leave", "Argue", "B"),
    _q(22, "A team conflict occurs. You should:", "Mediate", "Blame", "Avoid", "Quit", "A"),
    _q(23, "Under pressure, you should:", "Stay calm", "Panic", "Stop", "Leave", "A"),
    _q(24, "Family asks questions. You should:", "Explain clearly", "Ignore", "Mock", "Leave", "A"),
    _q(25, "Patient refuses care. You should:", "Listen and explain", "Force", "Ignore", "Delay", "A"),
    _q(26, "Heavy workload assigned. You should:", "Prioritize", "Complain", "Stop", "Delay", "A"),
    _q(27, "Instructions unclear. You should:", "Clarify", "Guess", "Ignore", "Delay", "A"),
    _q(28, "Peer needs help. You should:", "Assist", "Ignore", "Mock", "Report", "A"),
    _q(29, "Complication appears. You should:", "Assess", "Panic", "Blame", "Leave", "A"),
    _q(30, "Feedback is given. You should:", "Use it", "Argue", "Ignore", "Reject", "A"),
    _q(31, "Ethical issue arises. You should:", "Follow ethics", "Hide", "Ignore", "Delay", "A"),
    _q(32, "Patient upset emotionally. You should:", "Show empathy", "Ignore", "Judge", "Leave", "A"),
    _q(33, "Multiple options available. You should:", "Evaluate", "Random", "Delay", "Copy", "A"),
    _q(34, "Deadline pressure. You should:", "Manage time", "Panic", "Stop", "Blame", "A"),
    _q(35, "Critical case worsens. You should:", "Report immediately", "Ignore", "Delay", "Hide", "A"),
    _q(36, "Compassion improves:", "Patient care", "Graphics", "Audio", "Power", "A"),
    _q(37, "Critical thinking helps in:", "Decision making", "Cabling", "Audio", "Power", "A"),
    _q(38, "Emotional resilience means:", "Coping with stress", "Quitting", "Delay", "Blame", "A"),
    _q(39, "Patient advocacy means:", "Protecting patient rights", "Ignoring", "Delay", "Mock", "A"),
    _q(40, "Public health nursing focuses on:", "Community care", "Router", "Coding", "Audio", "A"),
    _q(41, "Company nurse role involves:", "Workplace health", "Painting", "Audio", "Power", "A"),
    _q(42, "Observation helps detect:", "Patient changes", "CPU heat", "Audio", "Network", "A"),
    _q(43, "Decision making uses:", "Assessment data", "Random", "Delay", "Blame", "A"),
    _q(44, "Teamwork ensures:", "Coordinated care", "Audio", "Graphics", "Power", "A"),
    _q(45, "Patient safety focuses on:", "Error prevention", "Delay", "Ignore", "Hide", "A"),
    _q(46, "Health promotion means:", "Prevention", "Random", "Delay", "Stop", "A"),
    _q(47, "Stress management improves:", "Performance", "Errors", "Delay", "Blame", "A"),
    _q(48, "Documentation ensures:", "Continuity of care", "Painting", "Audio", "Power", "A"),
    _q(49, "Observation identifies:", "Symptoms", "Cables", "Graphics", "Network", "A"),
    _q(50, "Professional responsibility means:", "Accountability", "Ignore", "Delay", "Copy", "A"),
]

# ── ECE (BSCPE / BSECE / BSCE) ───────────────────────────────────────────
ECE = [
    _q(1,  "Ohm's Law relates:", "Voltage, current, resistance", "Speed and time", "Mass and force", "Power and light", "A"),
    _q(2,  "A resistor is used to:", "Control current", "Store data", "Generate power", "Transmit signals", "A"),
    _q(3,  "Voltage is measured in:", "Volts", "Amperes", "Ohms", "Watts", "A"),
    _q(4,  "Current is measured in:", "Amperes", "Volts", "Ohms", "Hertz", "A"),
    _q(5,  "A capacitor stores:", "Electrical energy", "Light", "Sound", "Data", "A"),
    _q(6,  "A diode allows current to flow:", "One direction", "Two directions", "No direction", "Random", "A"),
    _q(7,  "Frequency is measured in:", "Hertz", "Volts", "Ohms", "Joules", "A"),
    _q(8,  "A transistor is used to:", "Amplify signals", "Cool systems", "Store files", "Draw diagrams", "A"),
    _q(9,  "A circuit requires:", "Closed path", "Open path", "No path", "Random path", "A"),
    _q(10, "Resistance is measured in:", "Ohms", "Volts", "Amperes", "Hertz", "A"),
    _q(11, "Digital signals are:", "Binary", "Analog", "Random", "Continuous", "A"),
    _q(12, "Analog signals are:", "Continuous", "Binary", "Fixed", "Random", "A"),
    _q(13, "PCB stands for:", "Printed Circuit Board", "Power Control Board", "Process Chip Base", "Program Code Block", "A"),
    _q(14, "Microcontrollers are used for:", "Control systems", "Audio only", "Graphics only", "Storage only", "A"),
    _q(15, "Signal processing deals with:", "Analyzing signals", "Painting", "Audio mixing only", "Power only", "A"),
    _q(16, "Communication systems transmit:", "Information", "Power only", "Heat", "Sound only", "A"),
    _q(17, "Troubleshooting identifies:", "Problems", "Design", "Graphics", "Audio", "A"),
    _q(18, "Instrumentation measures:", "Physical quantities", "Data storage", "Power", "Graphics", "A"),
    _q(19, "Simulation tools help:", "Test circuits", "Draw images", "Play audio", "Store data", "A"),
    _q(20, "Embedded systems are:", "Specialized systems", "General computers", "Network cables", "Audio tools", "A"),
    _q(21, "A project issue arises.", "Ignore", "Analyze problem", "Quit", "Delay", "B"),
    _q(22, "Team conflict occurs.", "Mediate", "Argue", "Avoid", "Leave", "A"),
    _q(23, "Deadline pressure increases.", "Manage time", "Panic", "Stop", "Delay", "A"),
    _q(24, "Instructions unclear.", "Clarify", "Guess", "Ignore", "Delay", "A"),
    _q(25, "Peer needs help.", "Assist", "Ignore", "Mock", "Report", "A"),
    _q(26, "New technology introduced.", "Learn it", "Resist", "Ignore", "Reject", "A"),
    _q(27, "Multiple solutions exist.", "Evaluate", "Random", "Delay", "Copy", "A"),
    _q(28, "System failure occurs.", "Troubleshoot", "Panic", "Blame", "Leave", "A"),
    _q(29, "Feedback given.", "Use feedback", "Ignore", "Argue", "Reject", "A"),
    _q(30, "Workload increases.", "Prioritize", "Complain", "Stop", "Delay", "A"),
    _q(31, "Error detected.", "Fix immediately", "Ignore", "Delay", "Hide", "A"),
    _q(32, "Team task assigned.", "Collaborate", "Ignore", "Leave", "Delay", "A"),
    _q(33, "Unexpected change occurs.", "Adapt", "Resist", "Stop", "Delay", "A"),
    _q(34, "Complex problem arises.", "Analyze", "Random", "Delay", "Copy", "A"),
    _q(35, "Critical system issue.", "Report quickly", "Ignore", "Delay", "Hide", "A"),
    _q(36, "Circuit analysis involves:", "Calculations", "Drawing only", "Audio", "Graphics", "A"),
    _q(37, "Electronics design focuses on:", "Creating circuits", "Painting", "Audio", "Power", "A"),
    _q(38, "Embedded systems require:", "Programming", "Cooking", "Audio", "Graphics", "A"),
    _q(39, "Signal processing improves:", "Signal quality", "Painting", "Audio only", "Power", "A"),
    _q(40, "Telecommunications uses:", "Signal transmission", "Drawing", "Audio", "Power", "A"),
    _q(41, "Microcontrollers execute:", "Programs", "Painting", "Audio", "Graphics", "A"),
    _q(42, "Debugging circuits means:", "Finding faults", "Drawing", "Audio", "Power", "A"),
    _q(43, "Instrumentation ensures:", "Accuracy", "Painting", "Audio", "Graphics", "A"),
    _q(44, "Simulation validates:", "Designs", "Painting", "Audio", "Power", "A"),
    _q(45, "System integration combines:", "Components", "Audio", "Graphics", "Power", "A"),
    _q(46, "Control systems regulate:", "Processes", "Painting", "Audio", "Graphics", "A"),
    _q(47, "Testing ensures:", "Functionality", "Painting", "Audio", "Power", "A"),
    _q(48, "Technical documentation records:", "System details", "Painting", "Audio", "Graphics", "A"),
    _q(49, "Engineering ethics ensures:", "Responsibility", "Ignore", "Delay", "Copy", "A"),
    _q(50, "Innovation involves:", "Creativity", "Copying", "Delay", "Ignore", "A"),
]

# ── Entrep (BSBA / BSHM) ─────────────────────────────────────────────────
ENTREP = [
    _q(1,  "Entrepreneurship primarily involves:", "Starting and managing a business", "Coding software", "Drawing", "Teaching", "A"),
    _q(2,  "Capital refers to:", "Funds used for business", "Products", "Customers", "Logos", "A"),
    _q(3,  "Profit is:", "Revenue minus expenses", "Total sales", "Cost", "Loss", "A"),
    _q(4,  "Marketing aims to:", "Promote products/services", "Store data", "Manufacture goods", "Hire staff", "A"),
    _q(5,  "A business plan outlines:", "Business strategy", "Graphic design", "Audio plan", "Network setup", "A"),
    _q(6,  "Demand refers to:", "Consumer desire for goods", "Supply", "Price only", "Cost only", "A"),
    _q(7,  "Supply refers to:", "Availability of goods", "Demand", "Price", "Cost", "A"),
    _q(8,  "Pricing affects:", "Sales and profit", "Audio", "Graphics", "Network", "A"),
    _q(9,  "Branding helps build:", "Business identity", "Cables", "Audio", "Power", "A"),
    _q(10, "Startup means:", "New business venture", "Old company", "Closed firm", "Network", "A"),
    _q(11, "Operations manage:", "Business processes", "Audio", "Graphics", "Design", "A"),
    _q(12, "Customer service ensures:", "Customer satisfaction", "Delay", "Stop", "Ignore", "A"),
    _q(13, "Innovation means:", "Creating new ideas", "Copying", "Delay", "Ignore", "A"),
    _q(14, "Risk-taking involves:", "Making uncertain decisions", "Delay", "Stop", "Ignore", "A"),
    _q(15, "Investment is:", "Allocating money for returns", "Spending randomly", "Loss", "Delay", "A"),
    _q(16, "Sales generate:", "Revenue", "Expense", "Asset", "Liability", "A"),
    _q(17, "Market research studies:", "Customer needs", "Graphics", "Audio", "Design", "A"),
    _q(18, "Entrepreneurs identify:", "Opportunities", "Cables", "Audio", "Power", "A"),
    _q(19, "Business growth means:", "Expansion", "Delay", "Stop", "Ignore", "A"),
    _q(20, "Strategy provides:", "Direction for business", "Random action", "Delay", "Stop", "A"),
    _q(21, "A product is not selling well.", "Ignore", "Analyze and adjust strategy", "Stop selling", "Blame others", "B"),
    _q(22, "Customer complains about service.", "Ignore", "Address concern professionally", "Argue", "Leave", "B"),
    _q(23, "Business faces competition.", "Give up", "Improve product/service", "Ignore", "Stop", "B"),
    _q(24, "Limited resources available.", "Plan efficiently", "Waste resources", "Delay", "Stop", "A"),
    _q(25, "Team conflict arises.", "Resolve calmly", "Argue", "Ignore", "Leave", "A"),
    _q(26, "Unexpected loss occurs.", "Analyze cause", "Panic", "Stop", "Ignore", "A"),
    _q(27, "New opportunity appears.", "Evaluate it", "Ignore", "Delay", "Stop", "A"),
    _q(28, "Feedback from customers.", "Use feedback", "Ignore", "Argue", "Reject", "A"),
    _q(29, "Market trend changes.", "Adapt strategy", "Ignore", "Stop", "Delay", "A"),
    _q(30, "Heavy workload.", "Prioritize tasks", "Complain", "Stop", "Delay", "A"),
    _q(31, "Business risk identified.", "Assess risk", "Ignore", "Delay", "Stop", "A"),
    _q(32, "New idea proposed.", "Explore idea", "Ignore", "Reject", "Delay", "A"),
    _q(33, "Sales decline.", "Investigate cause", "Ignore", "Stop", "Delay", "A"),
    _q(34, "Deadline pressure.", "Manage time", "Panic", "Stop", "Delay", "A"),
    _q(35, "Difficult client.", "Handle professionally", "Argue", "Ignore", "Leave", "A"),
    _q(36, "Opportunity recognition involves:", "Identifying business chances", "Delay", "Stop", "Ignore", "A"),
    _q(37, "Decision-making requires:", "Analysis", "Random", "Delay", "Stop", "A"),
    _q(38, "Strategic thinking helps:", "Long-term planning", "Delay", "Stop", "Ignore", "A"),
    _q(39, "Leadership involves:", "Guiding a team", "Delay", "Stop", "Ignore", "A"),
    _q(40, "Financial management ensures:", "Proper use of funds", "Delay", "Stop", "Ignore", "A"),
    _q(41, "Innovation drives:", "Business growth", "Delay", "Stop", "Ignore", "A"),
    _q(42, "Problem-solving resolves:", "Business issues", "Delay", "Stop", "Ignore", "A"),
    _q(43, "Communication improves:", "Clarity", "Delay", "Stop", "Ignore", "A"),
    _q(44, "Risk management reduces:", "Potential losses", "Delay", "Stop", "Ignore", "A"),
    _q(45, "Time management ensures:", "Productivity", "Delay", "Stop", "Ignore", "A"),
    _q(46, "Customer focus improves:", "Loyalty", "Delay", "Stop", "Ignore", "A"),
    _q(47, "Planning ensures:", "Organization", "Delay", "Stop", "Ignore", "A"),
    _q(48, "Adaptability helps:", "Handle change", "Delay", "Stop", "Ignore", "A"),
    _q(49, "Professionalism shows:", "Responsibility", "Delay", "Stop", "Ignore", "A"),
    _q(50, "Business evaluation involves:", "Analyzing performance", "Delay", "Stop", "Ignore", "A"),
]

# ── Psychology ────────────────────────────────────────────────────────────
PSYCHOLOGY = [
    _q(1,  "Psychological tests are primarily used to:", "Assess behavior/traits", "Repair hardware", "Design websites", "Route networks", "A"),
    _q(2,  "Validity refers to:", "Measures intended construct", "Test length", "Font style", "Speed only", "A"),
    _q(3,  "Reliability means:", "Consistency", "Randomness", "Creativity", "Network speed", "A"),
    _q(4,  "SPSS is used for:", "Statistical analysis", "Web design", "Circuit repair", "Animation", "A"),
    _q(5,  "Case documentation records:", "Client information", "CPU temperature", "Web code", "Audio", "A"),
    _q(6,  "Behavioral analysis studies:", "Behavior patterns", "Networks", "Graphics", "Batteries", "A"),
    _q(7,  "Counseling techniques help:", "Client support", "Cable repair", "Printing", "Database joins", "A"),
    _q(8,  "Research design guides:", "Study methods", "Routing", "Power", "Audio", "A"),
    _q(9,  "Likert scale measures:", "Attitudes", "Voltage", "Bandwidth", "Storage", "A"),
    _q(10, "Sampling concerns:", "Participant selection", "Server hosting", "Graphics", "Audio", "A"),
    _q(11, "Correlation indicates:", "Relationship", "Causation always", "Cable type", "Compiler", "A"),
    _q(12, "Interview is a:", "Data collection method", "Network protocol", "Database key", "CPU tool", "A"),
    _q(13, "Observation involves:", "Systematic watching", "Coding", "Subnetting", "Formatting", "A"),
    _q(14, "Ethics in psychology protect:", "Participants", "Cables", "Printers", "Power", "A"),
    _q(15, "Diagnosis involves:", "Assessment", "HTML", "Router", "Graphics", "A"),
    _q(16, "Psychometrics concerns:", "Measurement", "Cabling", "Audio", "Paper", "A"),
    _q(17, "Hypothesis is:", "Testable statement", "Database", "Device", "Language", "A"),
    _q(18, "Report writing communicates:", "Findings", "Voltage", "Audio", "Cables", "A"),
    _q(19, "Data interpretation means:", "Analyzing results", "Routing packets", "Drawing", "Printing", "A"),
    _q(20, "Mental health evaluation assesses:", "Psychological status", "Network load", "Battery", "Graphics", "A"),
    _q(21, "Client is distressed.", "Ignore", "Listen empathetically", "Argue", "Leave", "B"),
    _q(22, "Peer disagrees.", "Respectfully discuss", "Insult", "Avoid", "Quit", "A"),
    _q(23, "Confidential issue arises.", "Protect privacy", "Share publicly", "Ignore", "Post online", "A"),
    _q(24, "Heavy caseload occurs.", "Prioritize", "Panic", "Stop", "Delay", "A"),
    _q(25, "Ethical dilemma appears.", "Consult ethics", "Guess", "Hide", "Ignore", "A"),
    _q(26, "Team conflict occurs.", "Mediate", "Blame", "Leave", "Avoid", "A"),
    _q(27, "Client feedback given.", "Use feedback", "Argue", "Ignore", "Reject", "A"),
    _q(28, "Unexpected problem arises.", "Analyze options", "Panic", "Delay", "Quit", "A"),
    _q(29, "Sensitive topic discussed.", "Respond carefully", "Mock", "Ignore", "Judge", "A"),
    _q(30, "New method introduced.", "Adapt", "Resist", "Reject", "Delay", "A"),
    _q(31, "Client requests help.", "Assist appropriately", "Ignore", "Delay", "Blame", "A"),
    _q(32, "Multiple solutions exist.", "Evaluate", "Random pick", "Copy", "Stop", "A"),
    _q(33, "Communication misunderstood.", "Clarify", "Argue", "Leave", "Delay", "A"),
    _q(34, "Deadline pressure rises.", "Manage time", "Panic", "Stop", "Blame", "A"),
    _q(35, "Observation reveals risk.", "Report appropriately", "Ignore", "Hide", "Delay", "A"),
    _q(36, "Psychometric testing evaluates:", "Attributes", "Cables", "Audio", "Power", "A"),
    _q(37, "Emotional intelligence includes:", "Self-awareness", "Subnetting", "Coding", "Graphics", "A"),
    _q(38, "Active listening means:", "Attentive response", "Ignoring", "Interrupting", "Judging", "A"),
    _q(39, "Critical thinking involves:", "Evaluating evidence", "Random choice", "Guessing", "Delay", "A"),
    _q(40, "Problem solving starts with:", "Defining issue", "Blame", "Stop", "Panic", "A"),
    _q(41, "Empathy means:", "Understanding others", "Network routing", "Sorting", "Printing", "A"),
    _q(42, "Observation skill helps detect:", "Behavior cues", "CPU heat", "Audio", "Power", "A"),
    _q(43, "Interpersonal skills support:", "Relationships", "Cabling", "Graphics", "Voltage", "A"),
    _q(44, "Ethical decision making uses:", "Principles", "Randomness", "Delay", "Blame", "A"),
    _q(45, "Research assistant work includes:", "Data handling", "Cooking", "Painting", "Audio", "A"),
    _q(46, "Mental health support requires:", "Responsiveness", "Ignoring", "Delay", "Mocking", "A"),
    _q(47, "Case conceptualization means:", "Understanding case", "Routing", "Drawing", "Formatting", "A"),
    _q(48, "Behavior modification applies:", "Interventions", "Batteries", "Cables", "Audio", "A"),
    _q(49, "Counseling rapport builds:", "Trust", "Power", "Storage", "Graphics", "A"),
    _q(50, "Assessment interpretation uses:", "Analytical judgment", "Random guess", "Delay", "Copy", "A"),
]

ALL_QUESTIONS = {
    'BSCS':       BSCS,
    'BSIT':       BSIT,
    'BSA':        BSA,
    'BSEd':       BSED,
    'BSN':        BSN,
    'ECE':        ECE,
    'Entrep':     ENTREP,
    'Psychology': PSYCHOLOGY,
}
