"""
NCAE Skills Self-Rating Assessment — 1-5 scale (5 = Highest).
Alumni rate each statement about their own skills/abilities.

Structure per program: 50 statements
  Items  1-20 = Hard Skills   (technical/academic)
  Items 21-35 = Soft Skills   (professional/behavioral)
  Items 36-50 = Specific Skills (domain/tools)

Scoring:
  hard_score     = sum(ratings 1-20)  / (20 * 5) * 100
  soft_score     = sum(ratings 21-35) / (15 * 5) * 100
  specific_score = sum(ratings 36-50) / (15 * 5) * 100
  total_score    = sum(all 50 ratings) / (50 * 5) * 100
"""

PROGRAM_MAP = {
    'BSCS':  'BSCS',
    'BSIT':  'BSIT',
    'BSA':   'BSA',
    'BSBA':  'Entrep',
    'BSHM':  'Entrep',
    'BSEd':  'BSEd',
    'BEEd':  'BSEd',
    'BSN':   'BSN',
    'BSCPE': 'ECE',
    'BSECE': 'ECE',
    'BSCE':  'ECE',
    'BSEE':  'ECE',
    'BSME':  'ECE',
}

DEFAULT_PROGRAM = 'BSIT'


def get_program_key(course):
    return PROGRAM_MAP.get((course or '').upper().strip(), DEFAULT_PROGRAM)


def _r(num, statement):
    """Create a self-rating item (1 = poor, 5 = excellent)."""
    if num <= 20:
        cat = 'hard'
    elif num <= 35:
        cat = 'soft'
    else:
        cat = 'specific'
    return {'num': num, 'statement': statement, 'category': cat}


# ── BSCS ──────────────────────────────────────────────────────────────────
BSCS = [
    # Hard Skills — technical/academic competencies
    _r(1,  "My proficiency in at least one programming language (Python, Java, or C++)"),
    _r(2,  "My ability to analyze and solve algorithmic problems"),
    _r(3,  "My understanding of data structures (arrays, lists, trees, graphs)"),
    _r(4,  "My skill in debugging and fixing code errors"),
    _r(5,  "My knowledge of object-oriented programming principles"),
    _r(6,  "My proficiency in writing clean, well-structured code"),
    _r(7,  "My understanding of relational databases and SQL"),
    _r(8,  "My ability to use version control systems such as Git"),
    _r(9,  "My knowledge of software development lifecycle and methodologies"),
    _r(10, "My ability to design software systems and architectures"),
    _r(11, "My understanding of computer networks and protocols"),
    _r(12, "My knowledge of operating system concepts"),
    _r(13, "My ability to develop web applications (front-end and back-end)"),
    _r(14, "My understanding of algorithms and computational complexity"),
    _r(15, "My knowledge of software testing and quality assurance approaches"),
    _r(16, "My ability to work with REST APIs and web services"),
    _r(17, "My understanding of agile and scrum development processes"),
    _r(18, "My knowledge of cybersecurity fundamentals"),
    _r(19, "My ability to analyze requirements and translate them into code"),
    _r(20, "My proficiency in technical documentation writing"),
    # Soft Skills
    _r(21, "My ability to communicate technical ideas clearly to others"),
    _r(22, "My skill in working collaboratively as part of a development team"),
    _r(23, "My ability to manage my time and prioritize tasks effectively"),
    _r(24, "My adaptability when project scope or requirements change"),
    _r(25, "My composure and effectiveness when working under pressure or deadlines"),
    _r(26, "My openness to receiving and applying constructive feedback"),
    _r(27, "My initiative in learning new technologies independently"),
    _r(28, "My ability to organize and plan complex technical work"),
    _r(29, "My attention to detail in code review and documentation"),
    _r(30, "My confidence in presenting my work or findings to others"),
    _r(31, "My ability to help teammates resolve technical problems"),
    _r(32, "My persistence in solving difficult technical challenges"),
    _r(33, "My ability to handle multiple tasks or responsibilities at once"),
    _r(34, "My professionalism and reliability in a workplace setting"),
    _r(35, "My ability to collaborate effectively with non-technical stakeholders"),
    # Specific Skills — domain tools/applications
    _r(36, "My experience building full-stack web applications"),
    _r(37, "My knowledge of machine learning and data science concepts"),
    _r(38, "My experience with cloud platforms such as AWS, GCP, or Azure"),
    _r(39, "My proficiency in mobile application development"),
    _r(40, "My experience with DevOps, CI/CD pipelines, and automation"),
    _r(41, "My knowledge of containerization tools such as Docker or Kubernetes"),
    _r(42, "My experience with data analysis and visualization tools"),
    _r(43, "My proficiency in developing and consuming REST or GraphQL APIs"),
    _r(44, "My understanding of AI and machine learning model development"),
    _r(45, "My experience applying UI/UX design principles"),
    _r(46, "My knowledge of cybersecurity tools and ethical hacking concepts"),
    _r(47, "My experience with microservices and distributed systems"),
    _r(48, "My proficiency in database performance tuning"),
    _r(49, "My experience contributing to team projects or open-source repositories"),
    _r(50, "My ability to apply software engineering best practices in projects"),
]

# ── BSIT ──────────────────────────────────────────────────────────────────
BSIT = [
    # Hard Skills
    _r(1,  "My knowledge of computer networking fundamentals and the OSI model"),
    _r(2,  "My ability to configure and troubleshoot routers and switches"),
    _r(3,  "My proficiency in network security principles and practices"),
    _r(4,  "My understanding of server administration on Windows and Linux"),
    _r(5,  "My knowledge of database management systems and SQL"),
    _r(6,  "My ability to perform IT helpdesk and technical support tasks"),
    _r(7,  "My proficiency in scripting for IT automation using Python or Bash"),
    _r(8,  "My understanding of cloud computing concepts and services"),
    _r(9,  "My knowledge of cybersecurity threats and mitigation techniques"),
    _r(10, "My ability to install, configure, and maintain operating systems"),
    _r(11, "My proficiency in web technologies such as HTML, CSS, and JavaScript"),
    _r(12, "My understanding of virtualization and hypervisor technologies"),
    _r(13, "My knowledge of IT disaster recovery and backup solutions"),
    _r(14, "My ability to monitor and maintain IT systems and infrastructure"),
    _r(15, "My understanding of enterprise software and ERP systems"),
    _r(16, "My proficiency in technical documentation and reporting"),
    _r(17, "My knowledge of wireless network design and administration"),
    _r(18, "My understanding of IP addressing, subnetting, and routing protocols"),
    _r(19, "My ability to evaluate and recommend IT hardware and software solutions"),
    _r(20, "My knowledge of IT compliance and security standards"),
    # Soft Skills
    _r(21, "My ability to explain technical issues clearly to non-technical users"),
    _r(22, "My skill in working collaboratively within an IT team"),
    _r(23, "My ability to manage my time and prioritize support requests"),
    _r(24, "My adaptability when systems or technologies change unexpectedly"),
    _r(25, "My composure and effectiveness during system outages or emergencies"),
    _r(26, "My openness to receiving and applying feedback from supervisors"),
    _r(27, "My initiative in staying current with new IT technologies"),
    _r(28, "My ability to organize and document IT processes and procedures"),
    _r(29, "My attention to detail in system configurations and audit records"),
    _r(30, "My confidence in providing training or guidance to end users"),
    _r(31, "My ability to mentor junior IT team members"),
    _r(32, "My persistence in diagnosing complex technical issues"),
    _r(33, "My ability to handle multiple IT incidents simultaneously"),
    _r(34, "My professionalism in customer-facing IT support scenarios"),
    _r(35, "My ability to bridge technical and business communication gaps"),
    # Specific Skills
    _r(36, "My experience managing enterprise servers and server roles"),
    _r(37, "My knowledge of network security tools such as firewalls, VPNs, and IDS"),
    _r(38, "My experience with cloud infrastructure on AWS, Azure, or GCP"),
    _r(39, "My proficiency in cybersecurity assessment and penetration testing tools"),
    _r(40, "My experience with database administration using MySQL or PostgreSQL"),
    _r(41, "My knowledge of IT service management frameworks such as ITIL"),
    _r(42, "My experience with virtualization platforms such as VMware or Hyper-V"),
    _r(43, "My proficiency in designing and implementing LAN/WAN infrastructure"),
    _r(44, "My knowledge of IoT devices and protocols"),
    _r(45, "My experience with network monitoring and management tools"),
    _r(46, "My proficiency in PowerShell or Bash scripting for automation"),
    _r(47, "My understanding of ERP and enterprise application integration"),
    _r(48, "My experience responding to and recovering from cybersecurity incidents"),
    _r(49, "My knowledge of wireless security standards and protocols"),
    _r(50, "My experience deploying and managing web and application servers"),
]

# ── BSA ───────────────────────────────────────────────────────────────────
BSA = [
    # Hard Skills
    _r(1,  "My knowledge of fundamental accounting principles and the accounting cycle"),
    _r(2,  "My ability to prepare and analyze financial statements"),
    _r(3,  "My proficiency in journal entries, bookkeeping, and ledger management"),
    _r(4,  "My understanding of auditing standards and procedures"),
    _r(5,  "My knowledge of taxation laws and BIR compliance in the Philippines"),
    _r(6,  "My ability to perform financial analysis and ratio analysis"),
    _r(7,  "My proficiency in accounting software such as QuickBooks or SAP"),
    _r(8,  "My understanding of cost accounting and management accounting"),
    _r(9,  "My knowledge of internal control systems and fraud prevention"),
    _r(10, "My ability to reconcile accounts and manage bank statements"),
    _r(11, "My understanding of PFRS and GAAP standards"),
    _r(12, "My proficiency in Excel spreadsheets for financial work"),
    _r(13, "My knowledge of payroll accounting and labor law compliance"),
    _r(14, "My ability to prepare tax returns and compliance reports"),
    _r(15, "My understanding of business law as it applies to accounting"),
    _r(16, "My ability to evaluate financial viability and projections"),
    _r(17, "My knowledge of cash flow management and budgeting"),
    _r(18, "My proficiency in preparing audit working papers"),
    _r(19, "My understanding of government accounting standards"),
    _r(20, "My knowledge of financial reporting and disclosure requirements"),
    # Soft Skills
    _r(21, "My ability to communicate financial information clearly to management"),
    _r(22, "My skill in working as part of an accounting or finance team"),
    _r(23, "My ability to manage deadlines during audit and reporting periods"),
    _r(24, "My adaptability when accounting standards or procedures change"),
    _r(25, "My composure and accuracy when working under time pressure"),
    _r(26, "My openness to receiving feedback on financial work"),
    _r(27, "My initiative in staying current with accounting regulations"),
    _r(28, "My ability to organize financial records systematically"),
    _r(29, "My attention to detail in calculations and financial documents"),
    _r(30, "My confidence in presenting financial findings to stakeholders"),
    _r(31, "My ability to mentor or guide junior accounting staff"),
    _r(32, "My persistence in resolving accounting discrepancies"),
    _r(33, "My ability to handle multiple reporting tasks simultaneously"),
    _r(34, "My professionalism and adherence to ethical accounting standards"),
    _r(35, "My ability to work with clients and understand their business needs"),
    # Specific Skills
    _r(36, "My experience preparing full financial statements (income, balance sheet, cash flow)"),
    _r(37, "My proficiency in external or internal auditing engagements"),
    _r(38, "My knowledge of managerial accounting tools and cost analysis"),
    _r(39, "My experience with enterprise accounting systems such as SAP or Oracle"),
    _r(40, "My proficiency in tax planning and BIR electronic filing"),
    _r(41, "My knowledge of forensic accounting and fraud examination"),
    _r(42, "My experience with government auditing under COA standards"),
    _r(43, "My ability to analyze investment portfolios and financial instruments"),
    _r(44, "My proficiency in risk-based audit approaches"),
    _r(45, "My knowledge of international financial reporting standards (IFRS)"),
    _r(46, "My experience with payroll systems and HR accounting integration"),
    _r(47, "My ability to conduct due diligence and business valuations"),
    _r(48, "My knowledge of cash management and bank reconciliation"),
    _r(49, "My proficiency in budgeting and financial forecasting"),
    _r(50, "My experience conducting financial reviews and compliance checks"),
]

# ── BSEd (General) ────────────────────────────────────────────────────────
BSED = [
    # Hard Skills
    _r(1,  "My ability to develop clear and achievable learning objectives"),
    _r(2,  "My proficiency in creating detailed and organized lesson plans"),
    _r(3,  "My knowledge of different instructional strategies and teaching methods"),
    _r(4,  "My ability to design and conduct formative and summative assessments"),
    _r(5,  "My understanding of curriculum development and design principles"),
    _r(6,  "My knowledge of Bloom's Taxonomy and its classroom application"),
    _r(7,  "My ability to manage classroom dynamics and student behavior"),
    _r(8,  "My proficiency in differentiating instruction for diverse learners"),
    _r(9,  "My understanding of learning theories and child/adolescent psychology"),
    _r(10, "My ability to use educational technology in teaching"),
    _r(11, "My knowledge of assessment tools and rubric design"),
    _r(12, "My ability to deliver clear and engaging lessons"),
    _r(13, "My understanding of the K-12 curriculum framework"),
    _r(14, "My proficiency in motivating and sustaining student engagement"),
    _r(15, "My knowledge of special education needs and inclusive teaching practices"),
    _r(16, "My ability to evaluate student performance objectively"),
    _r(17, "My proficiency in developing instructional materials and aids"),
    _r(18, "My understanding of educational research and its classroom application"),
    _r(19, "My knowledge of guidance and counseling practices in schools"),
    _r(20, "My ability to align lessons to DepEd or institutional standards"),
    # Soft Skills
    _r(21, "My ability to communicate clearly and effectively with students"),
    _r(22, "My skill in collaborating with co-teachers and school staff"),
    _r(23, "My ability to manage my time and prepare lessons well in advance"),
    _r(24, "My adaptability when class schedules or learning needs change"),
    _r(25, "My patience and composure when managing a challenging classroom"),
    _r(26, "My openness to receiving feedback from supervisors or mentors"),
    _r(27, "My initiative in pursuing professional development opportunities"),
    _r(28, "My ability to organize learning activities and classroom materials"),
    _r(29, "My attention to detail in grading and record-keeping"),
    _r(30, "My confidence in handling parent-teacher conferences"),
    _r(31, "My ability to support struggling students with empathy"),
    _r(32, "My persistence in finding better ways to explain difficult concepts"),
    _r(33, "My ability to handle multiple classroom responsibilities simultaneously"),
    _r(34, "My professionalism and positive role modeling for students"),
    _r(35, "My ability to communicate with parents and community stakeholders"),
    # Specific Skills
    _r(36, "My experience in actual classroom or practice teaching"),
    _r(37, "My proficiency in using DepEd instructional materials and tools"),
    _r(38, "My knowledge of formative assessment strategies such as exit tickets"),
    _r(39, "My experience integrating technology into lessons using Google Classroom"),
    _r(40, "My proficiency in teaching my major subject area"),
    _r(41, "My knowledge of learner-centered and student-centered teaching approaches"),
    _r(42, "My experience in action research or classroom-based research"),
    _r(43, "My ability to use assessment data to guide and adjust instruction"),
    _r(44, "My knowledge of values education and character development integration"),
    _r(45, "My experience in co-curricular or extracurricular program coordination"),
    _r(46, "My proficiency in preparing students for national or board examinations"),
    _r(47, "My knowledge of SPED strategies and inclusive education practices"),
    _r(48, "My experience with school community outreach or extension activities"),
    _r(49, "My proficiency in school reporting systems such as LIS or LRNMS"),
    _r(50, "My experience participating in school-based management and planning"),
]

# ── BSN ───────────────────────────────────────────────────────────────────
BSN = [
    # Hard Skills
    _r(1,  "My knowledge of anatomy, physiology, and pathophysiology"),
    _r(2,  "My ability to accurately assess patient vital signs"),
    _r(3,  "My proficiency in medication dosage calculation and safe administration"),
    _r(4,  "My knowledge of nursing care plans and clinical documentation"),
    _r(5,  "My ability to perform sterile techniques and infection control procedures"),
    _r(6,  "My understanding of the nursing process from assessment to evaluation"),
    _r(7,  "My proficiency in IV insertion, wound care, and other clinical procedures"),
    _r(8,  "My knowledge of emergency response and basic life support skills"),
    _r(9,  "My understanding of pharmacology and drug interactions"),
    _r(10, "My ability to apply triage principles in emergency situations"),
    _r(11, "My knowledge of maternal and child health nursing"),
    _r(12, "My proficiency in medical-surgical nursing care"),
    _r(13, "My understanding of community and public health nursing"),
    _r(14, "My knowledge of mental health and psychiatric nursing"),
    _r(15, "My ability to interpret diagnostic tests and laboratory results"),
    _r(16, "My understanding of patient safety and hospital quality standards"),
    _r(17, "My proficiency in patient health education and teaching"),
    _r(18, "My knowledge of occupational health and company nursing"),
    _r(19, "My ability to document patient care using health information systems"),
    _r(20, "My understanding of nursing ethics and patient rights"),
    # Soft Skills
    _r(21, "My ability to communicate clearly with patients and their families"),
    _r(22, "My skill in working as part of a multidisciplinary healthcare team"),
    _r(23, "My ability to manage multiple patients and prioritize care effectively"),
    _r(24, "My adaptability when patient conditions change unexpectedly"),
    _r(25, "My composure and effectiveness in emergency clinical situations"),
    _r(26, "My openness to feedback from supervising nurses or physicians"),
    _r(27, "My initiative in staying current with evidence-based nursing practices"),
    _r(28, "My ability to organize nursing tasks and follow care protocols"),
    _r(29, "My attention to detail in medication preparation and clinical records"),
    _r(30, "My confidence in educating patients about their health conditions"),
    _r(31, "My ability to support and mentor student nurses"),
    _r(32, "My resilience when managing emotionally difficult clinical cases"),
    _r(33, "My ability to handle high patient loads during peak hours"),
    _r(34, "My professionalism and therapeutic demeanor in patient care settings"),
    _r(35, "My ability to advocate for patient rights and welfare"),
    # Specific Skills
    _r(36, "My clinical experience in medical-surgical ward nursing"),
    _r(37, "My proficiency in administering IV medications and blood products"),
    _r(38, "My knowledge of operating room or ICU nursing procedures"),
    _r(39, "My experience in community health nursing and outreach programs"),
    _r(40, "My proficiency in maternal and child health nursing (OB-GYN, pediatrics)"),
    _r(41, "My knowledge of mental health nursing interventions and therapeutic communication"),
    _r(42, "My experience as a company or occupational health nurse"),
    _r(43, "My ability to perform advanced clinical assessment"),
    _r(44, "My knowledge of nursing informatics and electronic health record systems"),
    _r(45, "My experience in disaster or mass casualty nursing"),
    _r(46, "My proficiency in therapeutic communication with patients"),
    _r(47, "My knowledge of nursing research and evidence-based practice"),
    _r(48, "My experience in geriatric or long-term care nursing"),
    _r(49, "My proficiency in CPR and advanced cardiac life support"),
    _r(50, "My knowledge of infection prevention and control protocols"),
]

# ── ECE (BSCPE / BSECE / BSCE) ───────────────────────────────────────────
ECE = [
    # Hard Skills
    _r(1,  "My understanding of basic circuit theory including Ohm's Law and Kirchhoff's Laws"),
    _r(2,  "My proficiency in analyzing and designing analog and digital electronic circuits"),
    _r(3,  "My knowledge of microcontrollers and embedded systems"),
    _r(4,  "My understanding of signals, systems, and signal processing theory"),
    _r(5,  "My proficiency in reading and interpreting circuit schematics and diagrams"),
    _r(6,  "My knowledge of communication systems and signal transmission principles"),
    _r(7,  "My ability to use electronic test equipment such as oscilloscopes and multimeters"),
    _r(8,  "My understanding of power electronics and electrical machines"),
    _r(9,  "My knowledge of control systems and feedback control theory"),
    _r(10, "My proficiency in PCB design, layout, and prototyping"),
    _r(11, "My understanding of digital signal processing (DSP) concepts"),
    _r(12, "My knowledge of wireless communications and RF systems"),
    _r(13, "My ability to program microcontrollers such as Arduino, PIC, or ARM"),
    _r(14, "My understanding of semiconductor devices and their applications"),
    _r(15, "My knowledge of instrumentation, measurement, and transducer systems"),
    _r(16, "My proficiency in simulation tools such as MATLAB, Multisim, or SPICE"),
    _r(17, "My understanding of electromagnetic theory and field applications"),
    _r(18, "My knowledge of telecommunications network infrastructure and protocols"),
    _r(19, "My ability to apply engineering standards and safety regulations"),
    _r(20, "My proficiency in engineering mathematics and applied physics"),
    # Soft Skills
    _r(21, "My ability to explain engineering concepts clearly to teammates or clients"),
    _r(22, "My skill in working effectively as part of an engineering project team"),
    _r(23, "My ability to manage project timelines and meet technical deadlines"),
    _r(24, "My adaptability when project specifications or technical constraints change"),
    _r(25, "My composure and systematic thinking when technical problems arise"),
    _r(26, "My openness to feedback during design reviews and testing phases"),
    _r(27, "My initiative in learning new engineering tools and technologies"),
    _r(28, "My ability to plan, document, and manage engineering projects"),
    _r(29, "My attention to detail in circuit design, testing, and verification"),
    _r(30, "My confidence in presenting engineering designs to supervisors or clients"),
    _r(31, "My ability to mentor junior engineers or fellow students"),
    _r(32, "My persistence in troubleshooting and resolving technical faults"),
    _r(33, "My ability to manage multiple engineering tasks simultaneously"),
    _r(34, "My professionalism in adhering to engineering ethics and standards"),
    _r(35, "My ability to collaborate effectively with technicians, contractors, and clients"),
    # Specific Skills
    _r(36, "My experience designing and testing analog or digital circuits"),
    _r(37, "My proficiency in embedded systems programming using C or Assembly"),
    _r(38, "My knowledge of telecommunications tower and transmission systems"),
    _r(39, "My experience with PLCs and industrial automation systems"),
    _r(40, "My proficiency in PCB layout using tools such as KiCad or Altium"),
    _r(41, "My knowledge of 5G, IoT, and wireless communication standards"),
    _r(42, "My experience with FPGA design and HDL programming (VHDL or Verilog)"),
    _r(43, "My proficiency in digital signal processing applications"),
    _r(44, "My knowledge of power systems and electrical distribution"),
    _r(45, "My experience with robotics and mechatronics systems"),
    _r(46, "My proficiency in MATLAB and Simulink for system modeling and simulation"),
    _r(47, "My knowledge of RF and microwave engineering principles"),
    _r(48, "My experience in network planning and telecommunications infrastructure"),
    _r(49, "My proficiency in CAD or CAE tools for engineering design"),
    _r(50, "My experience completing a capstone or major engineering project"),
]

# ── Entrep (BSBA / BSHM) ─────────────────────────────────────────────────
ENTREP = [
    # Hard Skills
    _r(1,  "My knowledge of fundamental business and entrepreneurship principles"),
    _r(2,  "My ability to develop and write a comprehensive business plan"),
    _r(3,  "My understanding of financial management and basic accounting"),
    _r(4,  "My proficiency in market research and consumer analysis"),
    _r(5,  "My knowledge of sales strategies and customer acquisition"),
    _r(6,  "My ability to develop and manage product or service pricing strategies"),
    _r(7,  "My understanding of operations management and business process design"),
    _r(8,  "My knowledge of supply chain and logistics management"),
    _r(9,  "My ability to apply marketing concepts and digital marketing strategies"),
    _r(10, "My understanding of business law and regulatory compliance"),
    _r(11, "My proficiency in financial statement preparation and analysis"),
    _r(12, "My knowledge of human resource management and team building"),
    _r(13, "My ability to identify and evaluate business opportunities"),
    _r(14, "My understanding of startup ecosystems and sources of funding"),
    _r(15, "My knowledge of risk management and business contingency planning"),
    _r(16, "My ability to develop marketing campaigns and build brand identity"),
    _r(17, "My understanding of e-commerce and digital business models"),
    _r(18, "My knowledge of competitive analysis and industry positioning"),
    _r(19, "My ability to forecast sales and prepare financial projections"),
    _r(20, "My understanding of negotiation principles and contract management"),
    # Soft Skills
    _r(21, "My ability to communicate business ideas persuasively to others"),
    _r(22, "My skill in building and leading an entrepreneurial team"),
    _r(23, "My ability to manage time and meet business milestone deadlines"),
    _r(24, "My adaptability when market conditions or customer needs change"),
    _r(25, "My resilience and determination when facing business setbacks"),
    _r(26, "My openness to feedback from mentors, customers, or investors"),
    _r(27, "My initiative in identifying and acting on business opportunities"),
    _r(28, "My ability to organize business operations and administrative processes"),
    _r(29, "My attention to detail in contracts, finances, and business records"),
    _r(30, "My confidence in pitching business ideas to investors or partners"),
    _r(31, "My ability to build and maintain professional business relationships"),
    _r(32, "My creativity in developing innovative solutions to business problems"),
    _r(33, "My ability to make sound decisions under uncertainty"),
    _r(34, "My professionalism in business dealings and client interactions"),
    _r(35, "My ability to negotiate effectively with suppliers, partners, and clients"),
    # Specific Skills
    _r(36, "My experience creating and executing a real business or detailed business plan"),
    _r(37, "My proficiency in digital marketing tools such as social media and SEO"),
    _r(38, "My knowledge of financial modeling and business valuation"),
    _r(39, "My experience with customer service and client relationship management"),
    _r(40, "My proficiency in conducting market surveys and consumer research"),
    _r(41, "My knowledge of import/export processes and international trade regulations"),
    _r(42, "My experience managing day-to-day business operations"),
    _r(43, "My proficiency in using e-commerce platforms such as Shopee or Shopify"),
    _r(44, "My knowledge of franchise and licensing business models"),
    _r(45, "My experience fundraising or pitching to investors or accelerators"),
    _r(46, "My proficiency in brand development and visual identity creation"),
    _r(47, "My knowledge of HR processes including hiring, payroll, and employee relations"),
    _r(48, "My experience with government business registration and compliance"),
    _r(49, "My proficiency in business analytics and key performance indicator monitoring"),
    _r(50, "My experience leading or managing a team in a business context"),
]

# ── Psychology ────────────────────────────────────────────────────────────
PSYCHOLOGY = [
    # Hard Skills
    _r(1,  "My knowledge of major psychological theories and key theorists"),
    _r(2,  "My ability to apply psychological assessment tools and standardized tests"),
    _r(3,  "My understanding of research design and statistical analysis in psychology"),
    _r(4,  "My proficiency in case conceptualization and psychological report writing"),
    _r(5,  "My knowledge of counseling techniques and psychotherapeutic approaches"),
    _r(6,  "My understanding of psychopathology and clinical diagnostic criteria"),
    _r(7,  "My ability to interpret psychological test results accurately"),
    _r(8,  "My knowledge of developmental psychology across the lifespan"),
    _r(9,  "My understanding of social psychology and group dynamics"),
    _r(10, "My proficiency in behavioral assessment and observation methods"),
    _r(11, "My knowledge of neuropsychology and biological bases of behavior"),
    _r(12, "My ability to conduct structured and unstructured clinical interviews"),
    _r(13, "My understanding of ethical guidelines in psychological practice and research"),
    _r(14, "My proficiency in qualitative and quantitative data collection and analysis"),
    _r(15, "My knowledge of industrial-organizational (I/O) psychology principles"),
    _r(16, "My ability to write comprehensive and accurate psychological assessment reports"),
    _r(17, "My understanding of cognitive psychology, memory, and learning processes"),
    _r(18, "My knowledge of mental health laws and patient rights in the Philippines"),
    _r(19, "My proficiency in psychological first aid and crisis intervention"),
    _r(20, "My understanding of personality theories and personality assessment"),
    # Soft Skills
    _r(21, "My ability to communicate empathetically with clients and respondents"),
    _r(22, "My skill in collaborating with multidisciplinary mental health teams"),
    _r(23, "My ability to manage caseloads and documentation deadlines effectively"),
    _r(24, "My adaptability when handling unexpected or sensitive client situations"),
    _r(25, "My composure and objectivity when managing emotionally difficult cases"),
    _r(26, "My openness to clinical supervision and professional feedback"),
    _r(27, "My initiative in pursuing continuing education in mental health"),
    _r(28, "My ability to organize client records and maintain strict confidentiality"),
    _r(29, "My attention to detail in psychological assessments and documentation"),
    _r(30, "My confidence in facilitating group discussions or psychoeducation sessions"),
    _r(31, "My ability to support clients in crisis while maintaining professional boundaries"),
    _r(32, "My resilience when dealing with vicarious trauma or compassion fatigue"),
    _r(33, "My ability to balance multiple client responsibilities simultaneously"),
    _r(34, "My professionalism in upholding psychological ethics and standards of practice"),
    _r(35, "My ability to communicate findings clearly to other professionals or families"),
    # Specific Skills
    _r(36, "My experience administering standardized psychological tests (IQ, personality)"),
    _r(37, "My proficiency in quantitative research using SPSS or similar statistical tools"),
    _r(38, "My knowledge of evidence-based therapy models such as CBT and SFBT"),
    _r(39, "My experience conducting intake interviews and comprehensive psychological assessments"),
    _r(40, "My proficiency in designing and implementing psychoeducation programs"),
    _r(41, "My knowledge of organizational behavior and HR psychological applications"),
    _r(42, "My experience conducting focus group discussions and qualitative interviews"),
    _r(43, "My proficiency in writing clinical case studies and formal psychological reports"),
    _r(44, "My knowledge of child and adolescent psychology and age-appropriate assessment"),
    _r(45, "My experience in career counseling and vocational guidance"),
    _r(46, "My proficiency in community mental health outreach and awareness programs"),
    _r(47, "My knowledge of trauma-informed care approaches"),
    _r(48, "My experience in school psychological services and student counseling"),
    _r(49, "My proficiency in applying I/O psychology in workplace assessment settings"),
    _r(50, "My experience in research assistance, data collection, or thesis analysis"),
]

ALL_QUESTIONS = {
    'BSCS':       BSCS,
    'BSIT':       BSIT,
    'BSA':        BSA,
    'BSEd':       BSED,
    'BSN':        BSN,
    'ECE':        ECE,
    'Entrep':     ENTREP,
    'Psychology': PSYCHOLOGY,
}
